##NumPy

NumPy is Python's fundamental package for scientific computing. Its core is the ndarray, a multi-dimensional array object, plus fast routines for math, logic, shape manipulation, sorting, selecting, I/O, Fourier transforms, linear algebra, statistics, and random simulation.

In [1]:
import numpy as np

1. Creating Arrays

In [3]:
arr = np.array(
    [1,2,3,4]
)

arr

array([1, 2, 3, 4])

In [8]:
arr = np.array(
    [1,2,3,4],dtype=int
)

arr

array([1, 2, 3, 4])

In [12]:
arr = np.arange(0,10,1) # returns arr in range | start , stop,step
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

.reshape(r, c) changes the shape of an array without changing its data.
- r = number of rows
- c = number of columns
 (2D)
- Total elements must remain the same.

In [22]:
arr = np.array(
   [1,2,3,4,5,6,7]
).reshape(7,1) # r c
arr

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

Important rule
The number of elements before and after must be equal.

6 elements

a.reshape(2, 3)   # 2 × 3 = 6

a.reshape(3, 2)   # 3 × 2 = 6

a.reshape(6, 1)   # 6 × 1 = 6

a.reshape(1, 6)   # 1 × 6 = 6

In [50]:
arr = np.zeros(3,dtype=np.int32) # 1D
arr

array([0, 0, 0], dtype=int32)

In [30]:
arr = np.zeros((2,3),dtype=int) #2D
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [31]:
arr = np.ones(4,dtype=int) # 1D
arr

array([1, 1, 1, 1])

In [32]:
arr = np.ones((2,3),dtype=int) #2D
arr


array([[1, 1, 1],
       [1, 1, 1]])

In [35]:
arr = np.ones((2,3,4),dtype=int) # 3D
arr

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

Random values between 0 and 1

In [39]:
arr = np.random.random((2,3))
arr

array([[0.65925435, 0.27342333, 0.83630327],
       [0.67760049, 0.7580362 , 0.31087055]])

Identity matrix (1s on the diagonal, 0s elsewhere)

In [41]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

2. Array Attrributes

In [52]:
arr = np.array(
    [[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]]
)

print("Dimensions : ",arr.ndim)
print("size :",arr.shape)
print("Total Number of elements Size: ",arr.size)
print("Data Type: ",arr.dtype)
print("Bytes Size:",arr.itemsize)


Dimensions :  2
size : (2, 9)
Total Number of elements Size:  18
Data Type:  int64
Bytes Size: 8


3.Changing data types (astype)

Converting to a smaller type, such as int64 to int32 for an age column, saves memory. This matters for big datasets, and check column dtypes whenever importing data.

10 million ages

int64:
10,000,000 × 8 = 80 MB

int32:
10,000,000 × 4 = 40 MB

In [54]:
arr = np.array(
    [20,25,30],dtype = np.int64
)
print(arr.itemsize)

new_arr = arr.astype(np.int32)
print(new_arr.itemsize)

8
4


4. Array  Operations

 - Scalar operations.
  = A scalar is just one number.

In [58]:
a = np.array(
    [1,2,3,4,5,6,7,8]
)
#Scalar operation = one number applied to every element.
print(a + 5)
print(a - 5)
print(a * 2)
print(a / 10)
print(a % 3)
print(a ** 2)
print(a > 20)

[ 6  7  8  9 10 11 12 13]
[-4 -3 -2 -1  0  1  2  3]
[ 2  4  6  8 10 12 14 16]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8]
[1 2 0 1 2 0 1 2]
[ 1  4  9 16 25 36 49 64]
[False False False False False False False False]


- vector operations

In [66]:
a = np.array(
    [1,2,3,4,5,6,7,8]
)

b = np.array(
    [1,2,3,4,5,6,7,8]
)


print(a+b)
print(a-b)
print(a*b)
print(a**b)
print(a//2)
print(a/2)

[ 2  4  6  8 10 12 14 16]
[0 0 0 0 0 0 0 0]
[ 1  4  9 16 25 36 49 64]
[       1        4       27      256     3125    46656   823543 16777216]
[0 1 1 2 2 3 3 4]
[0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


Scalar: array + number

Vector: array + array element-by-element.

5. Mathematical functions

In [73]:
arr = np.array(
    [1,2,3,4,5,6,7,8,9]
)
print("Basic")
print("="*10)
print("max: ",np.max(arr))
print("min: ",np.min(arr))
print("sum of all element: ", np.sum(arr))
print("product: ",np.prod(arr))

print("Statistics")
print("="*10)
print("mean: ",np.mean(arr))
print("median: ",np.median(arr))
print("standard deviation: ",np.std(arr))
print("variance: ",np.var(arr))


Basic
max:  9
min:  1
sum of all element:  45
product:  362880
Statistics
mean:  5.0
median:  5.0
standard deviation:  2.581988897471611
variance:  6.666666666666667


Axis Parameter

In [74]:
#Axis parameter: axis=0 works column-wise and axis=1 works row-wise.

a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[50 70 90]
[ 60 150]


1. np.sum()
2. np.mean()
3. np.min()
4. np.max()
5. np.median()
6. np.std()
7. np.var()
8. np.sqrt()
9. np.abs()
10. np.round()
11. np.floor()
12. np.ceil()
13. np.exp()
14. np.log()
15. np.clip()
16. np.dot(a, b)

Idexing and slicing

Indexing = select specific element(s)

Slicing = select a range of elements

In [78]:
arr = np.array(
   [1,2,3,4,5,6,7,8]
)

print(arr[0])
print("Negative Indexing: ", arr[-1])

1
Negative Indexing:  8


Slicing

In [84]:
arr = np.array(
   [1,2,3,4,5,6,7,8]
)

#print(arr[start:stop:step])
print(arr[1:6:2])
print(arr[1:6])


[2 4 6]
[2 3 4 5 6]


In [89]:
arr = np.array(
   [1,2,3,4,5,6,7,8]
)

print(arr[:4])
print(arr[4:])
print(arr[:])
print(arr[::2]) #It takes every 2nd element.
print(arr[::-1])


[1 2 3 4]
[5 6 7 8]
[1 2 3 4 5 6 7 8]
[1 3 5 7]
[8 7 6 5 4 3 2 1]


In [90]:
arr = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

print(arr[:2])       # first 2 rows
print(arr[2:])       # from row 2
print(arr[:])        # all rows
print(arr[::2])      # every 2nd row
print(arr[::-1])     # reverse rows

print(arr[:2, :2])   # first 2 rows, first 2 columns
print(arr[:, 1])     # all rows, column 1
print(arr[::2, ::2]) # every 2nd row and column

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[1 2]
 [5 6]]
[ 2  6 10 14]
[[ 1  3]
 [ 9 11]]


In [91]:
arr = np.array([
    [[1,2,3], [4,5,6]],
    [[7,8,9], [10,11,12]]
])

print(arr[:1])        # first block
print(arr[1:])        # from block 1
print(arr[:])         # all blocks
print(arr[::2])       # every 2nd block
print(arr[::-1])      # reverse blocks

print(arr[:, :1, :])  # all blocks, first row
print(arr[:, :, :2]) # all blocks, all rows, first 2 columns
print(arr[:, ::2, ::2]) # every 2nd row and column

[[[1 2 3]
  [4 5 6]]]
[[[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[1 2 3]
  [4 5 6]]]
[[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]
[[[1 2 3]]

 [[7 8 9]]]
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]
[[[1 3]]

 [[7 9]]]


 Iterating over arrays

In [92]:

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


In [93]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


In [94]:
arr = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


for x in arr:→ gives the next dimension

for x in np.nditer(arr):→ gives individual elements

Reshaping

Transpose: np.transpose(a) or a.T swaps rows and columns.

Ravel: flattens an array of any dimension into 1D.
These operations return a new result and don't change the original unless you assign it.


In [95]:


a = np.array([[1, 2, 3],
              [4, 5, 6]])

# Transpose
b = np.transpose(a)
print(b)

# or
b = a.T
print(b)

# Ravel
c = np.ravel(a)
print(c)

# or
c = a.ravel()
print(c)

# Original array is unchanged
print(a)

# To change the original, assign the result
a = a.T
print(a)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


-- Stacking (joining arrays)

Horizontal stack (hstack) joins side by side, so row counts must match.
Vertical stack (vstack) joins top to bottom, so column counts must match.
Useful for combining data from multiple sources, such as a database, an API, and web scraping.


In [96]:

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# Horizontal stack - side by side
c = np.hstack((a, b))
print(c)

# Vertical stack - top to bottom
d = np.vstack((a, b))
print(d)

# Horizontal stack → row count must match
# Vertical stack → column count must match

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
